/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.jaksonlin.jacocoparser;


import com.github.jaksonlin.jacocoparser.model.ClassCodeCoverage;
import com.github.jaksonlin.jacocoparser.model.JacocoReport;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class TestJacocoReport {
    @Test
    public void TestBasicCreate(){
        try{

            String url="http://127.0.0.1:28080/html/index.html";
            JacocoReport report = JacocoReport.newJacocoReportFromURL(url);
            report.loadSubReports();
            if (report.getReportContent().isEmpty()) {
                System.out.println("TestBasicCreate failed");
                Assert.fail();
            }
        } catch (Exception e){
            e.printStackTrace();
            Assert.fail();
        }

    }
    @Test
    public void TestClassCoverageCollection(){
        try{
            String url="http://127.0.0.1:28080/html/index.html";
            JacocoReport report = JacocoReport.newJacocoReportFromURL(url);
            report.loadSubReports();
            List<ClassCodeCoverage> cov = report.collectClassCodeCoverage();
            if (cov.isEmpty()) {
                System.out.println("TestClassCoverageCollection failed");
                Assert.fail();
            }
            for (ClassCodeCoverage c : cov) {
                if (c.getClassName().isEmpty()) {
                    Assert.fail();
                }
                if (c.getPackageName().isEmpty()) {
                    Assert.fail();
                }
            }
        }catch (Exception e){
            e.printStackTrace();
            Assert.fail();
        }
    }
}
